### ISSUE TITLE
Rename variable 2

### ISSUE THREAD

**Issue by bondrewd** [ToruNiina/Mjolnir#9]
What about changing "chain" to group and "group" to selection?
chain -> group
group -> selection

The reason is that sometimes the user does not have a "chain" but rather a more "abstract" (or complex) structure.

**Comment by ToruNiina** [comment]
It make sence. In some cases, like having a cyclic molecule, it is not a "chain".

I think this issue is not about "PDBChain" because it is exactly a chain. So your point is about a class that defines which particles are ignored in a global interaction. Right? In this context, currently `chain` means a set of beads that are bonded contiguously (mathematically, it is a connected graph).

But I'm a little worried that users might be confused. Because in most use cases, it is a chain. And I think `group` is so abstract that it can mean any kind of "group" of beads, like a pair of beads that are on a different molecules.
How about "molecule"? Do you have any idea about a word that means a set of particles that are bonded contiguously?

**Comment by bondrewd** [comment]
From Wikipedia:
A molecule is an electrically neutral group of two or more atoms held together by chemical bonds.

What about "mol" and "macromol"? 

Wikipedia:
A macromolecule is a very large molecule, such as protein, commonly created by the polymerization of smaller subunits (monomers).

**Comment by ToruNiina** [comment]
renamed.
